import { Button, VerticalBox, HorizontalBox, LineEdit, GroupBox, StandardListView, ListView} from "std-widgets.slint";

export struct Line  {
        name: int,
        value: string
    }


export component App inherits Window {
    width: 800px;
    height: 500px;

    in property <[Line]> lines;
    in property <string> name;
    in property <string> console;

    callback txtchng(int, string);
    callback subm_clicked <=> submit.clicked;
    callback save_clicked <=> save.clicked;
    callback load_clicked <=> load.clicked;
    callback get_clicked <=> get.clicked;


    VerticalBox {

    HorizontalBox {
        submit := Button { 
            text: "Send";
            height: 50px;
            width:47%;
        }

        save := Button {
            text: "Save";
            height: 50px;
            width:47%;
        }}
    HorizontalBox {

        load := Button {
            text: "Load";
            height: 50px;
            width:47%;
        }

        get := Button {
            text: "Get from device";
            width:47%;
            height: 50px;
        }
    }

    GroupBox {
        padding: 10px;
        vertical-stretch: 0;
            ListView {
            has-focus: false;
            vertical-stretch: 1;
            for it in lines: 
                HorizontalLayout {
                    padding-bottom:10px;
                    LineEdit {
                        padding-right:10px;

                        font-size: 38px;
                        read-only: true;
                        text: it.name;
                        width: 10%;
                    }
                    
                    LineEdit {
                        padding:10px;

                        placeholder-text:"Enter";
                        text: it.value;
                        font-size: 38px;

                        accepted(string) => {txtchng(it.name, string);}
                            }
                        }
            }
        }

        Text {
            text: console;   
            height: 30px;
        }



    }

    
}