[package]
name = "esp-midi-front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io_bluetooth = "0.1.0"
native-dialog = "0.7.0"
serde_json = "1.0.113"
slint = "1.4.1"
